export const bannedEmails = [
  "hibrahymdaniel@gmail.com",
  "therocklobo@gmail.com",
  "thelunapass@gmail.com",
  "kharu4735@gmail.com",
  "ti14bookmega@gmail.com",
  "atop127@yandex.ru",
  "giftaghedo71@gmail.com",
  "scottevbaru@gmail.com",
  "evbaru2@gmail.com",
  "ogieva.igho@yahoo.com",
  "ryaeiou100199@gmail.com",
  "ciangsabin@gmail.com",
  "izcipara88@gmail.com",
  "therockhidder@gmail.com",
  "deryanuwu7@gmail.com",
  "amox@poczta.fm",
  "hmbsamd@gmail.com",
  "sinosfirst@gmail.com",
  "xtremecharro1@gmail.com",
  "iceman89icm@gmail.com",
  "computronfromhell@gmail.com",
  "cirssimson@gmail.com",
  "therockcharro@gmail.com",
  "scallopedpotato1@gmail.com",
  "satywin8@gmail.com",
  "wn9m1@airsworld.net",
  "fistikfitil@gmail.com",
  "citobi3572@icousd.com",
  "aldi23sgg@gmail.com",
  "8wtsm@virgilian.com",
  "pisap71129@gavrom.com",
  "kitchen.home.garden@gmail.com",
  "fabiandonado2016@gmail.com",
  "ismailaltin611@gmail.com",
  "kaansamat85@gmail.com",
  "miraccakici66@gmail.com",
  "bilapek931@imfaya.com",
  "cosmicwindow.channel@gmail.com",
  "cokgensil@gmail.com",
  "fn2p1@airsworld.net",
  "sebastiananda14@gmail.com",
  "peshesabi.co@gmail.com",
  "airdroptest995@gmail.com",
  "onssatis@gmail.com",
  "chreko639@gmail.com",
  "cakicimirac61@gmail.com",
  "karalavuk5@gmail.com",
  "miraccakici611a@gmail.com",
  "goldhop444@gmail.com",
  "3rszn@airsworld.net",
  "parijih552@icousd.com",
  "36mgv@virgilian.com",
  "tarihimaraton@gmail.com",
  "karafatal356@gmail.com",
  "olja.naeratus@gmail.com",
  "ujsqu@airsworld.net",
  "melshock40@gmail.com",
  "poho08018@gmail.com",
  "airdropmetis11@gmail.com",
  "cullpwend0@gmail.com",
  "ssamat61@gmail.com",
  "tz8u0@airsworld.net",
];

export const placeholderplayerData = [
  {
    position: "0",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "1",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "2",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "3",
    displayName: "...",
    reward: "---",
    statValue: "---",
    premium: false,
  },

  {
    position: "4",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "5",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "6",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "7",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "8",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
  {
    position: "9",
    displayName: "...",
    reward: "---",
    premium: false,
    statValue: "---",
  },
];

export const dummyPremiums = [
  {
    chestTitle: "Jewel Coffer",
    closedImg: "greenCrystal",
    chestId: 1,
  },
  {
    chestTitle: "Gold Hoard",
    closedImg: "blueCrystal",
    chestId: 2,
  },
  {
    chestTitle: "Pirate's Bounty",
    closedImg: "yellowCrystal",
    chestId: 3,
  },
  {
    chestTitle: "Gem Trove",
    closedImg: "purpleCrystal",
    chestId: 4,
  },
  {
    chestTitle: "Coin Chest",
    closedImg: "cyanCrystal",
    chestId: 5,
  },
  {
    chestTitle: "Silver Cache",
    closedImg: "greenCrystal",
    chestId: 6,
  },
  {
    chestTitle: "Ruby Stash",
    closedImg: "blueCrystal",
    chestId: 7,
  },
  {
    chestTitle: "Mystic Reliquary",
    closedImg: "yellowCrystal",
    chestId: 8,
  },
  {
    chestTitle: "Ancient Relics",
    closedImg: "purpleCrystal",
    chestId: 9,
  },
  {
    chestTitle: "Emerald Trove",
    closedImg: "cyanCrystal",
    chestId: 10,
  },
];
