/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar.glb -o src/components/Avatar.jsx -r public 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const { scene } = useGLTF("/models/avatar.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);



  const { animations: talkAnimation } = useFBX("/animations/talk.fbx");
  const { animations: idleAnimation } = useFBX("/animations/testIdle.fbx");
  const { animations: standingIdleAnimation } = useFBX("/animations/Standing Idle.fbx");


  talkAnimation[0].name = "Talk";
  idleAnimation[0].name = "Idle";
  standingIdleAnimation[0].name = "StandingIdle";

  const [animation, setAnimation] = useState("Idle");
  const group = useRef();

  const { actions } = useAnimations(
    [idleAnimation[0], talkAnimation[0]],
    group
  );

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    clone.scale.set(1, 1, 1); // Ensure the scale remains consistent
    clone.position.set(0, 0, 0); // Reset position
    return () => actions[animation].fadeOut(0.5);
    
  }, [animation]);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.eyeleft.geometry}
        material={materials.Std_Cornea_L1}
        skeleton={nodes.eyeleft.skeleton}
      />
      <skinnedMesh
        geometry={nodes.eyeright.geometry}
        material={materials.Std_Cornea_L1}
        skeleton={nodes.eyeright.skeleton}
      />
      <skinnedMesh
        geometry={nodes.gloveL.geometry}
        material={materials.spymask1}
        skeleton={nodes.gloveL.skeleton}
      />
      <skinnedMesh
        geometry={nodes.gloveR.geometry}
        material={materials.spymask1}
        skeleton={nodes.gloveR.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Jacket.geometry}
        material={materials.futureClothes}
        skeleton={nodes.Jacket.skeleton}
      />
      <skinnedMesh
        geometry={nodes.mask1.geometry}
        material={materials["mask:spymask1"]}
        skeleton={nodes.mask1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Pants.geometry}
        material={materials.futureClothes}
        skeleton={nodes.Pants.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Shirt.geometry}
        material={materials.futureClothes}
        skeleton={nodes.Shirt.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Shoe_Left.geometry}
        material={materials.futureClothes}
        skeleton={nodes.Shoe_Left.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Shoe_Right.geometry}
        material={materials.futureClothes}
        skeleton={nodes.Shoe_Right.skeleton}
      />
      <skinnedMesh
        geometry={nodes.shoulderL.geometry}
        material={materials.spymask1}
        skeleton={nodes.shoulderL.skeleton}
      />
      <skinnedMesh
        geometry={nodes.shoulderR.geometry}
        material={materials.spymask1}
        skeleton={nodes.shoulderR.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh008.geometry}
        material={materials.black}
        skeleton={nodes.Mesh008.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh008_1.geometry}
        material={materials.blueglow}
        skeleton={nodes.Mesh008_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh.geometry}
        material={materials.Ga_Skin_Head}
        skeleton={nodes.Mesh.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh_1.geometry}
        material={materials.Ga_Skin_Body1}
        skeleton={nodes.Mesh_1.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/models/avatar.glb");
